server:
  port: 9999

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?userUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: password
    #   链接池
    hikari:
      #      链接池名字
      pool-name: DateHikariCP
      #      最小链接数字
      minimum-idle: 5
      #      空闲链接存活的最大时间 默认（600000） 10分钟
      idle-timeout: 180000
      #      最大链接数
      maximum-pool-size: 10
      #      从链接池返回的链接自动提交
      auto-commit: true
      #      链接最大存活时间 0 就是永久存活，默认是（180000）30分钟
      max-lifetime: 180000
      #      链接超时时间
      connection-timeout: 30000
      #      测试链接是否可以用
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    #    默认第0个库
    database: 0
    #    超时
    timeout: 10000ms
    lettuce:
      pool:
        #        默认最大链接数
        max-active: 8
        #         默认最大链接等待时间 -1
        max-wait: 10000ms
        #        最小空闲 默认0
        min-idle: 5
mybatis-plus:
  #  xml文件位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #  映射别名的位置
  type-aliases-package: com.myself.seckill.entity

#log日志 mybatis sql 打印（方法所在接口包，不是xml文件所在地方）
logging:
  level:
    com.myself.seckill.mapper: debug
# 显示所有的健康检查 资源
management:
  endpoint:
    health:
      show-details: always
# 开启所有的默认检查配置
  endpoints:
    web:
      exposure:
        include: '*'
        # 如果只想打开几个配置 那么编写需要打开的配置的名字，用逗号分割 env,info
#        include: env,info

info.s: y
info.test: myTest
#定义项目相关信息
info.app-Name: Seckill
info.author: AT
info.email: 1234567@qq.com
#使用 连字符 分割配置文件
---
spring:
  profiles:
    active: dev
server:
  tomcat:
    max-connections: 100
---
spring:
  profiles:
    active: prod
server:
  tomcat:
    max-connections: 200